/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   20
#define gattdb_board_rev                      22
#define gattdb_firmware_rev                   24
#define gattdb_system_id                      26
#define gattdb_aio_digital_in                 29
#define gattdb_aio_num_of_digitals_in         32
#define gattdb_aio_digital_out                34
#define gattdb_aio_num_of_digitals_out        36
#define gattdb_batt_measurement               39
#define gattdb_power_source_type              43
#define gattdb_iaq_eco2                       46
#define gattdb_iaq_tvoc                       48
#define gattdb_hall_state                     51
#define gattdb_hall_field_strength            54
#define gattdb_hall_control_point             57
#define gattdb_imu_acceleration               60
#define gattdb_imu_orientation                63
#define gattdb_imu_control_point              66
#define gattdb_es_uvindex                     70
#define gattdb_es_ambient_light               72
#define gattdb_es_pressure                    74
#define gattdb_es_temperature                 76
#define gattdb_es_humidity                    78
#define gattdb_es_sound_level                 80
#define gattdb_ui_rgbleds                     83
#define gattdb_ota_control                    86


#endif // __GATT_DB_H
